name: LightHeadPlugin
version: ${project.version}
main: net.kunmc.lab.lighthetadplugin.LightHeadPlugin
api-version: 1.16
authors: [Peyang]
description: かるいあたま。
website: https://kunmc.net/

commands:
  head:
    description: プレイヤの頭をチョンパします！

permissions:
  lighthead:
    description: このプラグインのメインコマンドです。
    children:
      head: true
  lighthead.head:
    description: プレイヤの頭をチョンパします！
    default: true
